set(REALSENSE_ROOT "/home/luvision/library/librealsense-2.10.4" CACHE PATH "Root directory of libREALSENSE")

FIND_PATH(REALSENSE_INCLUDE_DIR libREALSENSE HINTS "${REALSENSE_ROOT}/include")
FIND_LIBRARY(REALSENSE_LIBRARY REALSENSE HINTS "${REALSENSE_ROOT}/bin/x64" "${REALSENSE_ROOT}/lib")

mark_as_advanced(REALSENSE_LIBRARY REALSENSE_INCLUDE_DIR)

